---
- hosts: pies
  user: pi
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - name: install aptitude
     apt:
      pkg:
        - aptitude
      state: present
      update_cache: yes
